version: '3.9'

networks:
  scss:
    driver: bridge

volumes:
  redis: {}

services:
  web:
    container_name: scss-api
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app
    networks:
      - scss

  redis:
    image: "redis:alpine"
    networks:
      - scss

  celery:
    container_name: scss-celery
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: celery -A server.tasks.app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - scss